name             'tal_java'
maintainer       'Talentica'
maintainer_email ''
license          'All rights reserved'
description      'Installs/Configures java'
long_description 'Wrapper cookbook for java'
version          '1.0.0'
depends		 'java'
